# Generated by Django 4.2.2 on 2023-06-20 04:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=120, verbose_name='Full name')),
                ('email', models.EmailField(max_length=120, verbose_name='Email')),
                ('subject', models.CharField(max_length=120, verbose_name='Subject')),
                ('message', models.TextField(max_length=120, verbose_name='Message')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
            ],
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='events/', verbose_name='Image')),
                ('title', models.CharField(max_length=100, verbose_name='Title Event')),
                ('price', models.PositiveIntegerField(verbose_name='Price')),
                ('description', models.TextField(max_length=200, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
            },
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='gallery/', verbose_name='Image')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
            ],
            options={
                'verbose_name': 'Photo',
                'verbose_name_plural': 'Gallery',
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='Name')),
                ('email', models.EmailField(max_length=150, verbose_name='Email')),
                ('phone', models.CharField(max_length=13, verbose_name='Phone')),
                ('date', models.DateField(verbose_name='Date')),
                ('time', models.TimeField(verbose_name='Time')),
                ('persons', models.PositiveSmallIntegerField(verbose_name='Persons')),
                ('message', models.TextField(max_length=500, verbose_name='Message')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
            ],
            options={
                'verbose_name': 'reserv',
                'verbose_name_plural': 'reservation',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='Role')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
            ],
            options={
                'verbose_name': 'Role',
                'verbose_name_plural': 'Roles',
            },
        ),
        migrations.CreateModel(
            name='Testimonials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='testimonials/', verbose_name='Image')),
                ('first_name', models.CharField(max_length=120, verbose_name='Firstname')),
                ('last_name', models.CharField(max_length=120, verbose_name='Lastname')),
                ('description', models.TextField(max_length=120, verbose_name='Theme')),
                ('profession', models.CharField(max_length=120, verbose_name='Profession')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
            ],
            options={
                'verbose_name': 'Testimonial',
                'verbose_name_plural': 'Testimonials',
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Тame of the dish')),
                ('image', models.ImageField(upload_to='food/', verbose_name='Image')),
                ('price', models.PositiveIntegerField(verbose_name='Price')),
                ('description', models.TextField(max_length=200, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='food.category', verbose_name='Category')),
            ],
            options={
                'verbose_name': 'Menu',
                'verbose_name_plural': 'Menu',
            },
        ),
        migrations.CreateModel(
            name='Chefs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='chefs/', verbose_name='Image')),
                ('full_name', models.CharField(max_length=100, verbose_name='Name')),
                ('twitter', models.URLField(blank=True, max_length=300, null=True, unique=True, verbose_name='twitter Url')),
                ('facebook', models.URLField(blank=True, max_length=300, null=True, unique=True, verbose_name='facebook Url')),
                ('instagram', models.URLField(blank=True, max_length=300, null=True, unique=True, verbose_name='instagram Url')),
                ('linkedin', models.URLField(blank=True, max_length=300, null=True, unique=True, verbose_name='linkedin Url')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='food.role', verbose_name='Role chef')),
            ],
            options={
                'verbose_name': 'Chef',
                'verbose_name_plural': 'Chefs',
            },
        ),
    ]
